export const events = pgTable("events", {
  eventId: serial("event_id").primaryKey(), // auto-increment
  id: text("id"), // from Dynamo
  year: integer("year"),
  ename: text("ename"),
  description: text("description"),
  startDate: timestamp("start_date"),
  endDate: timestamp("end_date"),
  deadline: timestamp("deadline"),
  createdAt: timestamp("created_at"),
  updatedAt: timestamp("updated_at"),
  location: text("elocation"),
  imageUrl: text("image_url"),
  facebookUrl: text("facebook_url"),
  isApplicationBased: boolean("is_application_based"),
  isPublished: boolean("is_published"),
  isCompleted: boolean("is_completed"),
  hasDomainSpecificQuestions: boolean("has_domain_specific_questions"),
  isPartnerFormUsed: boolean("is_partner_form_used"),
  latitude: text("latitude"),
  longitude: text("longitude"),
  pricing: jsonb("pricing"),
  registrationQuestions: jsonb("registration_questions"),
  partnerRegistrationQuestions: jsonb("partner_registration_questions"),
  partnershipsConfirmation: jsonb("partnerships_confirmation"),
  feedback: jsonb("feedback"),
  partnerDescription: text("partner_description"),
  capacity: integer("capacity"),
});
